### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by bbbco** [slackhq/magic-cli#1]
The blog post in the README references a Makefile that is used to install the tool. 

It would be great if a sample Makefile was included to help bootstrap the tool further!

**Comment by shinypb** [comment]
Thanks for pointing that out, @bbbco. I've put together a Makefile that can be used as a starting point in #3.

**Comment by shinypb** [comment]
This has been merged!

:sparkles: Thanks for making magic-cli better, @bbbco! :tophat:

**Comment by bbbco** [comment]
:+1:
