### ISSUE TITLE
How does/should magic-cli handle dependencies?

### ISSUE THREAD

**Issue by dwmarshall** [slackhq/magic-cli#5]
How do you manage dependencies that the tools require, e.g. Ruby gems that some `magic-foo` script might need? Do you install such dependencies using `Makefile`, or does each script typically determine whether its dependencies are available?

**Comment by shinypb** [comment]
Internally, we handle those in our Makefile; we have added a `install_deps` task that gets run automatically when you `make install` or `make install_quiet`. Here's an example of what that could look like: https://gist.github.com/shinypb/a2aad926e4e8a42f8b61cbcc808904d4
