### ISSUE TITLE
Sharing code between scripts

### ISSUE THREAD

**Issue by rknLA** [slackhq/magic-cli#9]
This is more a question than an issue, but with this "installable to /usr/local/bin" approach, have you figured out any best practices around sharing configuration between scripts? For example, to allow a set of scripts to `source common-foo.sh`

It seems that that sort of stuff shouldn't show up as a command at the root level, but should still be installed somewhere (also not likely a `bin` directory, right?)

**Comment by shinypb** [comment]
Sorry for the excessive delay. 😳 For our internal projects, we've ended up installing a support directory at `/usr/local/bin/<whatever>` full of files that various scripts source as needed. It's not great, but it works.
